services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME_PROD}"
      POSTGRES_USER: "${DB_USER_PROD}"
      POSTGRES_PASSWORD: "${DB_PASSWORD_PROD}"
      PGDATA: "/var/lib/postgresql/data/pgdatamarket"
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
      - emarket-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres
  emarket:
    build: .
    image: emarket_app:latest
    container_name: emarket_app_container
    env_file:
      - .env
    environment:
      DB_NAME_PROD: ${DB_NAME_PROD}
      DB_USER_PROD: ${DB_USER_PROD}
      DB_PASSWORD_PROD: ${DB_PASSWORD_PROD}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "sample@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

volumes:
  pgadmin-data:
  emarket-data:

networks:
  postgres:
    driver: bridge