spring:
  application:
    name: e-market
  datasource:
    url: "jdbc:postgresql://db:5432/emarket"
    username: emarketuser
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8080