CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    rating      FLOAT                                   NOT NULL,
    price       FLOAT                                   NOT NULL,
    user_id     INTEGER                                 NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE product_review
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255),
    rating     SMALLINT,
    body       VARCHAR(255),
    product_id BIGINT,
    CONSTRAINT pk_productreview PRIMARY KEY (id)
);

ALTER TABLE product_review
    ADD CONSTRAINT FK_PRODUCTREVIEW_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);