CREATE TABLE clothing
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    rating FLOAT                                   NOT NULL,
    price  FLOAT                                   NOT NULL,
    size_id     INTEGER,
    CONSTRAINT pk_clothing PRIMARY KEY (id)
);

CREATE TABLE clothing_review
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    rating      SMALLINT,
    body        VARCHAR(255),
    user_id     INTEGER                                 NOT NULL,
    clothing_id BIGINT,
    CONSTRAINT pk_clothingreview PRIMARY KEY (id)
);

CREATE TABLE size
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    size VARCHAR(255),
    CONSTRAINT pk_size PRIMARY KEY (id)
);

ALTER TABLE clothing_review
    ADD CONSTRAINT FK_CLOTHINGREVIEW_ON_CLOTHING FOREIGN KEY (clothing_id) REFERENCES clothing (id);

ALTER TABLE clothing
    ADD CONSTRAINT FK_CLOTHING_ON_SIZE FOREIGN KEY (size_id) REFERENCES size (id);